cartpole1 :
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 10
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 5
  discount_factor: 0.98
  learning_rate: 0.0001